# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodayNail' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodayNail
  pod 'FSCalendar'
  pod 'Tabman', '~> 2.12'

end
